# -*- coding: utf-8 -*-
"""winners_cleaned.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XxTJBDRIAXyjc1oHTgcxGPb9h1st7gb_
"""

# Importar librerías necesarias
import pandas as pd

# Cargar el CSV (ajustá el nombre si es distinto)
df = pd.read_csv('winners_cleaned.csv', sep=';')

# Mostrar las primeras filas
df.head()