# -*- coding: utf-8 -*-
"""runnerups_cleaned.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZldK7ijq9SwITFdn5SXijMrmv1PCy84s
"""

import pandas as pd

# Leer el CSV usando punto y coma como separador
df = pd.read_csv('runnerups_cleaned.csv', sep=';')

# Mostrar las primeras filas
df.head()

import matplotlib.pyplot as plt

# Gráfico de barras con cantidad de desafíos ganados por cada runner-up
df.plot(x='runner_up_drag_name', y='maxi_challenges_won', kind='bar', figsize=(10,5))
plt.title('Maxi Challenges Ganados por Runner-up')
plt.ylabel('Cantidad')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# Estadísticas generales
df.describe(include='all')

# Distribución por temporada (ejemplo)
df['season'].value_counts()

import matplotlib.pyplot as plt

# Gráfico de barras con cantidad de lip sync ganados por cada runner-up
df.plot(x='runner_up_drag_name', y='lip_sync_won', kind='bar', figsize=(10,5))
plt.title('Lip Sync Ganados por Runner-up')
plt.ylabel('Cantidad')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()